// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDML8dsG7hLO2O9OJNotpixcf6m__VeEjc',
    appId: '1:430391883094:web:1ca03fb4a3ede8882e52f7',
    messagingSenderId: '430391883094',
    projectId: 'flutterapplication2-f5f22',
    authDomain: 'flutterapplication2-f5f22.firebaseapp.com',
    storageBucket: 'flutterapplication2-f5f22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7xythkZFNBwXPJV35Nwgupj9Cqh5WPgY',
    appId: '1:430391883094:android:f1fc58f02b55e15b2e52f7',
    messagingSenderId: '430391883094',
    projectId: 'flutterapplication2-f5f22',
    storageBucket: 'flutterapplication2-f5f22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTtQFuxRrp0cytocQcD0fuYksbMzmvPWo',
    appId: '1:430391883094:ios:758ee194b706096b2e52f7',
    messagingSenderId: '430391883094',
    projectId: 'flutterapplication2-f5f22',
    storageBucket: 'flutterapplication2-f5f22.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTtQFuxRrp0cytocQcD0fuYksbMzmvPWo',
    appId: '1:430391883094:ios:758ee194b706096b2e52f7',
    messagingSenderId: '430391883094',
    projectId: 'flutterapplication2-f5f22',
    storageBucket: 'flutterapplication2-f5f22.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDML8dsG7hLO2O9OJNotpixcf6m__VeEjc',
    appId: '1:430391883094:web:996e37c982b5a79e2e52f7',
    messagingSenderId: '430391883094',
    projectId: 'flutterapplication2-f5f22',
    authDomain: 'flutterapplication2-f5f22.firebaseapp.com',
    storageBucket: 'flutterapplication2-f5f22.firebasestorage.app',
  );
}
