// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2qZ63FQw3mms8ps8BSAPhTy-cfGJ2HU0',
    appId: '1:1055158895977:web:88874969df4e099cec69f8',
    messagingSenderId: '1055158895977',
    projectId: 'flutterapplication2-69f03',
    authDomain: 'flutterapplication2-69f03.firebaseapp.com',
    storageBucket: 'flutterapplication2-69f03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9_fHRSVzJD14pp__mnL-F6yxw--wyPP8',
    appId: '1:1055158895977:android:243a8a8ea223b2feec69f8',
    messagingSenderId: '1055158895977',
    projectId: 'flutterapplication2-69f03',
    storageBucket: 'flutterapplication2-69f03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZaUZADnOvBn4-JecDJCcdPvhTFqc0K2g',
    appId: '1:1055158895977:ios:e6ffb2214cfe5808ec69f8',
    messagingSenderId: '1055158895977',
    projectId: 'flutterapplication2-69f03',
    storageBucket: 'flutterapplication2-69f03.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZaUZADnOvBn4-JecDJCcdPvhTFqc0K2g',
    appId: '1:1055158895977:ios:e6ffb2214cfe5808ec69f8',
    messagingSenderId: '1055158895977',
    projectId: 'flutterapplication2-69f03',
    storageBucket: 'flutterapplication2-69f03.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2qZ63FQw3mms8ps8BSAPhTy-cfGJ2HU0',
    appId: '1:1055158895977:web:a09b6f4b67f0ec99ec69f8',
    messagingSenderId: '1055158895977',
    projectId: 'flutterapplication2-69f03',
    authDomain: 'flutterapplication2-69f03.firebaseapp.com',
    storageBucket: 'flutterapplication2-69f03.firebasestorage.app',
  );

}